name: Submit BR Data
description: Upload analyzer JSON files for admin review and inclusion in BR_Data.
labels: ["intake", "pending-validation"]
body:
  - type: markdown
    attributes:
      value: |
        Please attach your `.json` files and provide event details.
        A GitHub Action will validate and open a PR for admins to review.
        Files will be placed under `apps/analyzer/BR_Data/` (the exact subfolder can be adjusted by admins).
  - type: input
    id: event
    attributes:
      label: Event name/date
      description: e.g., 2025-12-02, Week 3
      placeholder: Season X - Week Y (YYYY-MM-DD)
    validations:
      required: true
  - type: input
    id: teams
    attributes:
      label: Teams involved
      description: e.g., Team A vs Team B
      placeholder: Team 1 vs Team 2
    validations:
      required: true
  - type: textarea
    id: notes
    attributes:
      label: Notes
      description: Optional context or links.
  - type: markdown
    attributes:
      value: |
        Attach files below by dragging and dropping, or use the file picker.
